apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: spark-operator
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoicHJhZG92YWxtdXIiLCJwYXNzd29yZCI6ImdocF9VUnVIdWJTaTdXU0NyYzNtVmdhV090NVUyWWFtM040WGNxOHIiLCJlbWFpbCI6InByYWRvdmFsbXVyQGdtYWlsLmNvbSIsImF1dGgiOiJjSEpoWkc5MllXeHRkWEk2WjJod1gxVlNkVWgxWWxOcE4xZFRRM0pqTTIxV1oyRlhUM1ExVlRKWllXMHpUalJZWTNFNGNnPT0ifX19