FROM apache/spark:3.5.1-scala2.12-java11-python3-ubuntu

USER root

RUN pip3 install --no-cache-dir delta-spark==3.2.0

ENV PYSPARK_PYTHON=python3
ENV PYSPARK_DRIVER_PYTHON=python3

WORKDIR /opt/spark/work-dir

USER 185