apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service-api.yaml
  - service-console.yaml
  - ingress.yaml
  - wildcard-tls.yaml